### PR TITLE
fixes for omap5

### PR DESCRIPTION
**Pull request by mvduin**
This fixes some of the most glaring bugs for omap5 and lets e.g. "omapconf show opp" work normally.

Tested on omap5-uevm with kernel 4.7-rc7-letux

### CODE REVIEW

**Comment by nmenon** [comment]
Hi,
I need the commits to be have the Signed-off-by: Tag. Could you update the patches with the "Signed-off-by:" Tag and appropriate email ID and I can get these merged in.

**Comment by nmenon** [comment]
while at it, please also add information in commit message. stuff like opp data changes etc need to appropriately documented as to why the frequencies are changing.

**Comment by mvduin** [comment]
Will do. The opp data is simply heavily outdated: I found some old preliminary datasheet addendum with some of the values used in omapconf, but the public datasheet from april 2014 already used 1000 MHz for OPP_NOM_MPU.

The pmic stuff has also been broken over a year at least since 727b8e6bee3de0bd7428f23048f51aa29bbba8da changed TWL6030_I2C_BUS but apparently failed to notice there was also a TWL6035_I2C_BUS used by some of the twl6035 code.

BTW I'm still leaning heavily towards the idea of splitting the twl6035 code off into a separate palmas.c file since palmas really seems to have nothing to do with twl6030 other than the unfortunate similarity in part code. Since I just wanted to quickly fix it I ended up adding even more special cases for it but it doesn't feel like the right way forward. What's your opinion on this?

**Comment by nmenon** [comment]
overall the PMIC stuff should be probably board dependent - I was always planning on doing that, but it takes time to clean things up properly. Lets first get the basic support in place that works for you dont forget to keep the OMAP5-uevm alive, then we can probably work towards refactoring the PMIC code to be board dependent.. unfortunately, I dont have interns this year whom I could try and throw at this problem... and my time is kind of limited to do that level of massive cleanup. :(

**Pull request closed without merging**
